turn_light_to_matched_color:
  description: Changes the specified light(s) to match a prominent color from the image specifed.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    url:
      description: "URL of an image to use for color recognition. This must be specified if 'media_player' is not."
      example: https://f4.bcbits.com/img/a0581187129_10.jpg
    media_player:
      description: "A single entity ID for which to use the 'entity_picture' state for recognition. This must be specified if 'url' is not. If this is specified, 'host' must be set in the confgiguration."
      example: media_player.android_tv
    mode:
      description: (Optional) Changes the recognition mode.
      example: "'recognized' or 'complementary'"
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"
turn_light_to_random_color:
  description: Changes the specified light(s) to a random color.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    mode:
      description: (Optional) Changes the color space for the returned color.
      example: "'rgb_color' or 'hs_color'"
    range_hue:
      description: (Optional) Clamp hue value in the specified range.
      example: 20, 120
    range_sat:
      description: (Optional) Clamp saturation value in the specified range.
      example: 90
    range_red:
      description: (Optional) Clamp red value in the specified range.
      example: 192, 240
    range_green:
      description: (Optional) Clamp green value in the specified range.
      example: 32, 168
    range_blue:
      description: (Optional) Clamp blue value in the specified range.
      example: 27, 255
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"