turn_light_to_matched_color:
  description: Changes the specified light(s) to match a prominent color from the image specifed.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    url:
      description: URL of an image to use for color recognition.
      example: https://f4.bcbits.com/img/a0581187129_10.jpg
    mode:
      description: (Optional) Changes the recognition mode.
      example: "'recognized' or 'complementary'"
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"
turn_light_to_random_color:
  description: Changes the specified light(s) to a random color.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    mode:
      description: (Optional) Changes the color space for the returned color.
      example: "'rgb_color' or 'hs_color'"
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"