turn_light_to_matched_color:
  description: Changes the specified light to match a prominent color from the image specifed.
  fields:
    entity_id:
      description: entity_id of the light you wish to change.
      example: light.living_room
    url:
      description: URL of an image to use for color recognition.
      example: https://i.scdn.co/image/ab67616d00001e028692b52d4f1a5d072e095b28
    mode:
      description: (Optional) Changes the recognition mode.
      example: "'recognized' or 'complementary'"
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"
turn_light_to_random_color:
  description: Changes the specified light to a random color.
  fields:
    entity_id:
      description: entity_id of the light you wish to change.
      example: light.living_room
    mode:
      description: (Optional) Changes the color space for the returned color.
      example: "'rgb_color' or 'hs_color'"
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"