turn_light_to_matched_color:
  description: Changes the specified light(s) to match a prominent color from the image specifed.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    url:
      description: "URL of an image to use for color recognition. This must be specified if 'media_player' is not."
      example: https://f4.bcbits.com/img/a0581187129_10.jpg
    media_player:
      description: "A single entity ID for which to use the 'entity_picture' state for recognition. This must be specified if 'url' is not. If this is specified, 'host' must be set in the confgiguration."
      example: media_player.android_tv
    host:
      description: "(Optional) Override 'host' from configuration. Can only be used with 'media_player'."
      example: "http://192.168.1.42:8123"
    mode:
      description: (Optional) Changes the recognition mode.
      example: "'recognized' or 'complementary'"
    same_color:
      description: (Optional) Set all lights to the same color.
      example: "'true' or 'false'"
    brightness:
      description: (Optional) A brightness value (0-255) to force lights to be set to.
      example: 192
    brightness_pct:
      description: (Optional) A brightness percentage (0-100) to force lights to be set to.
      example: 75
turn_light_to_random_color:
  description: Changes the specified light(s) to a random color.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    hs_color:
      description: (Optional) A dictionary of either ints or int lists, corresponding to each color component.
      example: "hue: 30, saturation: [60, 90]"
    rgb_color:
      description: (Optional) A dictionary of either ints or int lists, corresponding to each color component.
      example: "red: 30, green: [60, 90], blue: [75]"
    brightness:
      description: (Optional) An int or list of ints (0-255) to clamp random brightness between.
      example: "[32, 192]"
    brightness_pct:
      description: (Optional) An int or list of ints (0-100) to clamp random brightness percentage between.
      example: 75
turn_light_to_cycle_color:
  description: Cycles the specified light(s) along the hue spectrum.
  fields:
    entity_id:
      description: Entity ID(s) of the light(s) you wish to change.
      example: light.lamp
    steps:
      description: (Optional) Number of steps in the cycle.
      example: 24
    start:
      description: (Optional) Override starting hue.
      example: 180
    saturation:
      description: (Optional) An int or list of ints (0-100) to clamp random saturation between.
      example: "[32, 90]"
    brightness:
      description: (Optional) An int or list of ints (0-255) to clamp random brightness between.
      example: "[32, 192]"
    brightness_pct:
      description: (Optional) An int or list of ints (0-100) to clamp random brightness percentage between.
      example: 75